name: 'publish to dev.to'

on:
  workflow_dispatch:

concurrency:
  cancel-in-progress: true
  group: publish-${{ github.head_ref || github.ref }}

jobs:
  publish:
    name: publish new article
    runs-on: ubuntu-latest    
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      # - name: publish blog to dev.to
      #   uses: protiumx/blogpub@main
      #   with:
      #     articles_folder: blog
      #     devto_api_key: ${{ secrets.DEV_TO_GIT_TOKEN }}
      #     gh_token: ${{ secrets.GH_TOKEN }}
      # - name: Sycing Article to dev.to
      #   uses: ful1e5/TheActionDev@v3
      #   with:
      #     api-key: ${{ secrets.DEV_TO_GIT_TOKEN }} # Store your 'api-key' in Github Secret
      #     directory: ./blog # Your article directory
      #     ignore: Development.md, Production.md # Markdown file you wan't to ignore. Multple files separated by ,(comma)
      - name: Deploy to dev.to
        uses: sinedied/publish-devto@v2
        with:
          # Your dev.to personal API key to publish and update articles.
          # See https://docs.dev.to/api/#section/Authentication/api_key
          devto_key: ${{ secrets.DEV_TO_GIT_TOKEN }}
          # Your GitHub personal access token, used to create commits for updated files.
          # If you have a protected branch, you need to use a personal access token
          # with the 'repo' permission.
          # See https://docs.github.com/en/authentication/keeping-your-account-and-data-secure/creating-a-personal-access-token
          github_token: ${{ secrets.GH_TOKEN }}
          branch: main
          files: "blog/**/*.*"
          # (Optional) Use conventional commit messages. Default is false.
          # See https://www.conventionalcommits.org. 
          conventional_commits: true
          dry_run: false