name: 'publish to dev.to'

on:
  workflow_dispatch:
  push:
    branches:
      - 'main'
    paths:
      - 'blog/**'

concurrency:
  cancel-in-progress: true
  group: publish-${{ github.head_ref || github.ref }}

jobs:
  publish:
    name: publish new article
    runs-on: ubuntu-latest    
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: publish blog to dev.to
        uses: protiumx/blogpub@main
        with:
          articles_folder: blog
          devto_api_key: ${{ secrets.DEV_TO_GIT_TOKEN }}
          gh_token: ${{ secrets.GH_TOKEN }}